### ISSUE TITLE
Multiple MN on one VPS

### ISSUE THREAD

**Issue by jaapdevries** [adeptio-project/adeptio#4]
How would it be possible to run multiple MN's on one VPS?
Install script would break saying "Looks like you are trying to setup second time? You need a fresh installation!" and config will be altered with fresh IP?

https://github.com/adeptio-project/adeptio/blob/85f5bf2f14e56fb01af0a9a54c9bb862959253a3/scripts/setup_adeptio_hot_masternode_ipv4_latest.sh#L201

**Comment by adeptio-project** [comment]
No it's not possible. There are some "walk-arounds" and people use diff ports to recreate mn with another user with the same IP. Plus, they are not using installation scripts.
After general "storADE" release - **this problem will be fully patched**.

**Comment by komato3huk** [comment]
Hi this is big problem

**Comment by adeptio-project** [comment]
Fixed with new mandatory release:
https://github.com/adeptio-project/adeptio/releases

**Comment by skyfp133** [comment]
Sir,
Multiple MN on one VPS  Guide Step by Step With Pictures & all commands
