### ISSUE TITLE
getting IP returns no result

### ISSUE THREAD

**Issue by jaapdevries** [adeptio-project/adeptio#5]
wanip=$(/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com) does not return results on my VPS, when using the actual IP for resolver1.opendns.com it does work

wanip=$(/usr/bin/dig +short myip.opendns.com @208.67.222.222)

https://github.com/adeptio-project/adeptio/blob/8811bb977928614510342a2a665db0343eb9d551/scripts/setup_adeptio_hot_masternode_ipv4_latest.sh#L36

**Comment by jaapdevries** [comment]
In addition, perhaps allow a user to input the address by hand instead of exiting the script... Now you have to manually change the installation script, allowing for manual input would make it easier for some people to continue the installation process

**Comment by adeptio-project** [comment]
Can you provide more information?
`which dig ; wanip=$(/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com) ; echo $wanip`

**Comment by jaapdevries** [comment]
$ dig -v
DiG 9.10.6

**Comment by adeptio-project** [comment]
Can you copy all the line above and paste the output?

I am wondering why the result is completely empty.

**Comment by jaapdevries** [comment]
$ which dig ; wanip=$(/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com) ; echo $wanip
/usr/bin/dig


The dig command has no result, looks like @resolver1.opendns.com is not correctly routed

**Comment by adeptio-project** [comment]
Intresting situation. Perhaps your VPS or ISP somehow blocking the origin.
How about this alternative?
`wanip=$(curl -s 4.ipquail.com/ip) ; echo $wanip`

However, we will allow for manual input too

**Comment by jaapdevries** [comment]
I've tested the original command on:
KPN ISP from mac = empty result
Transip VPS = empty result
Digital Ocean (AMS3) = correct IP result

the alternative returns the correct ipv4 on all tests

**Comment by adeptio-project** [comment]
Changing the default method to:
`wanip=$(curl -s 4.ipquail.com/ip)`
Next release will be updated with manual input too. 
Thanks for help
